// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto15.models;

namespace Proyecto15.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    partial class ApplicationDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proyecto15.models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Proyecto15.models.CategoriaSubCategoria", b =>
                {
                    b.Property<int>("IdCategoriaSubCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdCategoria1")
                        .HasColumnType("int");

                    b.Property<int?>("IdSubCategoria1")
                        .HasColumnType("int");

                    b.HasKey("IdCategoriaSubCategoria");

                    b.HasIndex("IdCategoria1");

                    b.HasIndex("IdSubCategoria1");

                    b.ToTable("CategoriaSubCategorias");
                });

            modelBuilder.Entity("Proyecto15.models.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGrupo");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Proyecto15.models.Institucion", b =>
                {
                    b.Property<int>("IdInstitucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCategoriaSubCategoria1")
                        .HasColumnType("int");

                    b.Property<int?>("IdGrupo1")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdInstitucion");

                    b.HasIndex("IdCategoriaSubCategoria1");

                    b.HasIndex("IdGrupo1");

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("Proyecto15.models.SubCategoria", b =>
                {
                    b.Property<int>("IdSubCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSubCategoria");

                    b.ToTable("SubCategorias");
                });

            modelBuilder.Entity("Proyecto15.models.CategoriaSubCategoria", b =>
                {
                    b.HasOne("Proyecto15.models.Categoria", "IdCategoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria1");

                    b.HasOne("Proyecto15.models.SubCategoria", "IdSubCategoria")
                        .WithMany("CategoriaSubCategorias")
                        .HasForeignKey("IdSubCategoria1");
                });

            modelBuilder.Entity("Proyecto15.models.Institucion", b =>
                {
                    b.HasOne("Proyecto15.models.CategoriaSubCategoria", "IdCategoriaSubCategoria")
                        .WithMany()
                        .HasForeignKey("IdCategoriaSubCategoria1");

                    b.HasOne("Proyecto15.models.Grupo", "IdGrupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo1");
                });
#pragma warning restore 612, 618
        }
    }
}
